# SPDX-License-Identifier: GPL-3.0-or-later OR Commercial
# Copyright (C) 2026 Ayoub Achour
#
# Regenerate tb/random_vectors.h with AES-256 known-answer pairs for the
# Verilator harness to cross-check against pycryptodome.
#
# Run:  python tb/gen_random_vectors.py > tb/random_vectors.h
# Deps: pip install pycryptodome
from Crypto.Cipher import AES
import random

random.seed(0xC0FFEE)

print("// Auto-generated by tb/gen_random_vectors.py - do not edit by hand")
print("#pragma once")
print("#include <cstdint>")
print("struct RandomVec { const char* key; const char* pt; const char* ct; };")

vecs = []
for _ in range(100):
    k = bytes(random.getrandbits(8) for _ in range(32))   # 256-bit key
    p = bytes(random.getrandbits(8) for _ in range(16))
    c = AES.new(k, AES.MODE_ECB).encrypt(p)
    vecs.append((k.hex(), p.hex(), c.hex()))

print("static constexpr int kNumRandomVecs = %d;" % len(vecs))
print("static const RandomVec kRandomVecs[%d] = {" % len(vecs))
for k, p, c in vecs:
    print('  {"%s", "%s", "%s"},' % (k, p, c))
print("};")

print("static constexpr int kNumRoundtripPts = 1000;")
print("static const char* kRoundtripKeys[%d] = {" % 1000)
for _ in range(1000):
    print('  "%s",' % bytes(random.getrandbits(8) for _ in range(32)).hex())
print("};")
print("static const char* kRoundtripPts[%d] = {" % 1000)
for _ in range(1000):
    print('  "%s",' % bytes(random.getrandbits(8) for _ in range(16)).hex())
print("};")
